let distributeur = [
  {
    nom: "Coca Cola",
    prix: 1,
    image: "",
    description: "Soda gout cola",
    stock: 4,
    disponibilite: true,
  },
  {
    nom: "Fanta",
    prix: 1,
    image: "",
    description: "Soda gout orange",
    stock: 4,
    disponibilite: true,
  },
  {
    nom: "Sprit",
    prix: 1,
    image: "",
    description: "Soda gout citron",
    stock: 4,
    disponibilite: true,
  },
  {
    nom: "Coca Zero",
    prix: 1,
    image: "",
    description: "Soda gout cola sans sucre",
    stock: 4,
    disponibilite: true,
  },
  {
    nom: "Nestea",
    prix: 1,
    image: "",
    description: "Soda gout thé citron",
    stock: 4,
    disponibilite: true,
  },
  {
    nom: "Pepsi",
    prix: 1,
    image: "",
    description: "Soda gout cola",
    stock: 4,
    disponibilite: true,
  },
];
